
/*AUTOR: ANTONIO JESUS ZAFRA ARIAS*/
/*PROYECTO FINAL DESARROLLO DE APLICACIONES WEB*/
/*INTRODUCCION DE DATOS*/

use gimnasio;

/*INTRODUCIMOS DATOS DENTRO DE LA TABLA RECETA*/
INSERT INTO Receta(Nombre,Tipo,Ingredientes,Pasos,Tiempo_estimado,Nivel_Dificultad,Imagen)
Values

/*DESAYUNOS*/

/*RECETA 1*/
("PAN PROTEICO CON ACEITUNAS Y TOMATE SECO
","Desayuno","1 PAQUETE DE PAN PROTEICO VEGANO<br> 230ML  AGUA<br>100G ACEIUNTAS'(NEGRAS O VERDES)'<br>40G TOMATES DESHIDRATADOS<br> 1CDTA ORÉGANO SECO ","1º: MEZCLAR EL AGUA CON EL PREPARADO PARA PAN PROTEICO Y MEZCLAR BIEN HASTA LOGRAR UNA MASA HOMOGÉNEA<br><br>2º: CORTAR TANTO EL TOMATE COMO LAS ACEITUNAS EN PEQUEÑAS LÁMICAS Y AÑADIR A LA MASA ANTERIOR<br><br>3º:DARLE FORMA DE PAN A LA MASA Y COLOCAR SOBRE UNA BANDEJA DE HORNO O UN MOLDE PREVIAMENTE ENGRASADO<br><br>4º: HORNEAR EL PAN DE ACEITUNAS EN EL ESPACIO DENTRAL DEL HORNO PREVIAMENTE PRECALENTADO A 175 GRADOS. DEJAR HORNEAR SOBRE 50 MINUTOS <br><br>5º: DEJAR ENFRIAR Y CORTAR EN REBANADAS.DISFRUTAR DEL PAN, BIEN SOLO O ACOMPAÑADO CON CREMAS DE HUNTAR A NUESTRO GUSTO","60 MINUTOS","Facil","media/imagenes/pan_proteico.jpg"),


/*RECETA 2*/

("PUDDING DE AVENA AL CHOCOLATE","DESAYUNO","60G PORRIDE PROTEINCO CHOCOLATE<br>200ML AGUA<br>100ML LECHE DESNATADA<br>20G PUDDING DE CHOCOLTE EN POLVO<br> 20G BAYAS FRESCAS","1º:aJUNTAR EL PORRIDGE PROTEICO CON AGUA EN UNA OLLA E IR CALENTANDO LENTAMENTE.MEZCLAR BIEN<br><br>2º: BATIR LA LECHE CON EL PUDDING EN POLVO EN UN CUENCO Y AÑADIR DESPUES A LA OLLA PARA MEZCLARLO CON EL RESTO<br><br>3º: COCINAR EL PUDDING HASTA QUE VAYA ESPESANDO Y RETIRARLO A CONTINUACIÓN DEL FUEGO<br><br>4º: SERVIR EN UN CUENCO Y ADEREZAR CON TOPPINGS , AL GUSTO","10 minutos","Facil","media/imagenes/pudding_avena_chocolate.jpg"),

/*RECETA 3*/
("TORTITAS PROTEICAS RELLENAS DE CREMA","DESAYUNO","80GR TORTITAS PROTEICAS<br>130ML AGUA<BR>40G CREMA PROTEICA<br>10G ACEITE DE COCO","1º: MEZCLAR EL AGUA CON EL PREPARADO PARA TORTITAS EN UN SHAKER O EN UN CUENCO. BATIR BIEN HASTA QUE QUEDE UNA MEZCLA HOMOGÉNEA<br><br>2º: PONER A CALENTAR ACEITE DE COCO EN UNA SARTÉN<br><br>3º: AÑADIR A LA SARTÉN 2 CUCHARADAS DE LA MEZCLAS Y COLOCAR DENTRO DE CADA UNA UNA CUCHARADITA DE CREMA PROTEICA.  CUBRIR CADA UNA DE ELLAS NUEVAMENTE CON UNA CUCHARADA DE LA MASA DE TORTITAS. CERRAR LAS TORTITAS Y COCINARLAS<br><br> 4º: REPETIR EL PROCESO CON EL RESTO DE LA MASA<br><br>5º: SERVIR LAS TORTILLAS RELLENAS Y COMPLETAR CON TOPPINGS, AL GUSTO","15 MINUTOS","Facil","media/imagenes/tortitas_proteicas_rellenas_crema.jpg"),

/*ALMUERZO*/

/*RECETA 4*/
("PASTA PROTEICA CON GARBANZOS","ALMUERZO","60G ZANAHORIA<br>1/2 CEBOLLA<br>40G APIO EN RAMA<br>1CDA ACEITE DE OLIVA<br>130 G GARBANZOS DE LATA<br>1CDA CONCENTRADO DE TOMATE<br>500ML CALDO DE VERDURAS","1º:CORTAR LA ZANAHORIA, LA CEBOLLA Y EL APIO EN PEQUEÑOS DADOS<br><br>2º:PONER A CALENTAR ACEITE DE OLIVA EN UNA OLLA Y AÑADIRLE LA VERDURA TROCEADA Y LA RAIMA DE ROMERO. COCINAR 3 MINUTOS A FUEGO MEDIO<br><br>3º: AÑADIR AHORA LOS GARBANZOS, EL CONCENTRADO DE TOMATE Y 300 ML DE CALDO DE VERDURAS. COCINAR DURANTE OTROS 10 MINUTOS<br><br>4º:ECHAR EL CALDO DE VERDURA QUE FALTE POR AÑADIR Y PONER A HERVIR. ECHAR SAL Y AÑADIR LA PASTE. COCINAR DURANTE 7 MUNUTOS  HASTA QUE QUEDE AL DENTE<br><br>5º: ADEREZAR CON UN POCO DE PIMIENTA Y SERVIR","30 MINUTOS","Facil","media/imagenes/pasta_proteica_con_garbanzos.jpg"),

/*RECETA 5*/
("GAZPACHO FITNESS","ALMUERZO","4 REBANADAS PAN PROTEICO VEGANO<br>330G TOMATES DE RACIMO<br>60G PIMIENTO ROJO <br>130G PEPINO<br>1/4 CEBOLLA BLANCA<br>1/2 DIENTE DE AJO<br>200ML AGUA FRÍA<br> 1CDTA VINAGRE<br>1 CDA ACEITE DE OLIVA<br> SAL<br>PIMIENTA","1º: PREPARAR EL PAN PROTEICO DE ACUERDO A LA INSTRUCCIONES DEL ENVASE<br><br>2º: CORTAR LOS TOMATES, PIMENTO, PEPINO, AJO Y CEBOLLA EN PEQUEÑOS TROZOS<br><br>3º:MEZCLAR TODAS LAS VERDURAS CON AGUA, VINAGRE, ACEITE DE OLIVA, SAL Y PRIMIENTA CON UNA BATIDORA HASTA QUE QUEDE TODO HOMOGÉNEO<br><br>4º:SI ES NECESARIO, PASAR EL GAZPACHO POR UN COLADOR<br><br>5º:SERVIR EL GAZPACHO BEN FRÍO Y ADEREZAR AL GUSTO CON PIMIENTA Y DADITOS DE VERDURA<br><br>6º:TOSTAR EL PAN PROTEICO Y PARTIR DESPUÉS EN PEQUEÑOS PICATOSTES","60 MINUTOS","FACIL","media/imagenes/gazpacho_fitness.jpg"),

/*RECETA 6*/
("Rollitos de pizza","ALMUERZO","300G PIZZA PROTEICA<br>300ML AGUA TIBIA<br>10G LEVADURA FRESCA<br>200G SALSA DE TOMATE<br>100G MOZARELLA RALLADA<br>100G JAMON COCIDO<br>100G CHAMPIÑONES<br>ALBAHACA FRESCA","1º:AÑADE EL PREPARADO DE PIZZA EN UN BOL Y DEJA UN HUEVO EN EL CENTRO PARA INTRODUCIR EL AGUA. AÑÁDELE A ELLO LA LEVADURA Y HAZ QUE SE MEZCLA. DEJA REPOSAR DURANTE 10 MINUTOS<br><br>2º:TRANSFORMA TODO ELLO EN UNA MASA LISA, VE PRECALENTANDO EL HORNO A 180º<br><br>3º: EXTIENDE LA MASA DE PIZZA SOBRE UNA SUPERFICIO PLANA ESPOLVOREADA CON HARINA Y DALE LA FORMA DE UN RECTÁNGULO.AÑÁDELE SALSA DE TOMATE POR ENCIMA Y DESPUÉS EL RESTO DE AÑADIDOS<br><br>4º: ENROLLAR LA MASA POR EL LASO MÁS LARGO Y CORTAT EN LONCHAS DE 1-3CM DE GROSOR<br><br>5º: DEPOSITAR LOS ROLLITOS SOBRE EL PAPEL DE HORNEAR EN UNA BANDEJA DE HORNO Y HORNEAR DURANTE 20-25 MINUTOS","35 MINUTOS","FACIL","media/imagenes/rollitos_pizza.jpg"),

/*CENA*/

/*RECETA 7*/

("FILETES DE COLIFROR EMPANADOS","CENA","1 CABEZA DE COLIFLOR<br>100ML LECHA DE AENA, SIN AZÚCAR<br>40G COPOS DE PROTEÍNA<br> 1CDTA SAL<br>1CDTA PIMENTÓN<br>1CDTA CURRY EN POLVO<br>2 CDAS ACEITE DE OLVIDA<br>OPCIONAL:PEREJIL FRESCO, LIMÓN LECHUGA","1º: PRECALENTAR EL HORNO (ARRIBA Y ABAJO)A 180º<br><br>2º:RETIRAR LAS HOJS A LA CABEZA DE COLIFLOR. CORTARLE EL TALLO ÚNICAMENTE HASTA EL PUNTO EN EL QUE LA CABEZA DE COLIFLOR SE CONSIGA MANTENER EN PIE SOBRE LA TABLA DE CORTAR<br><br>3º:CORTAR 3 FILETES GRUESOS DE COLIFLOR. GUARDAR LAS PARTES RESTANTES Y RESERVARLAS PARA OTROS FINES<br><br>4º:VERTER LA LECHE DE AVENA EN UN PLATO GRANDE Y LLANO<br><br>5º:EN OTRO GRAN PLATO LLANO, ECHAR LOS COPOS DE PROTEÍNA.JUNTAR LA SAL, EL PIMENTÓN, EL CURRY EN POLVO Y EL AJO EN POLVO<br><br>6º:REBOZAR AHORA CADA UNO DE LOS FILETES DE COLIFLOR, PRIMERO REMOJÁNDOLOS EN LA LECHE Y DESPUÉS PASÁNDOLOS POR LOS COPOS DE PROTEÍNA POR AMBOS LADOS<br><br> 7º: RESERVAR LOS FILETES SEPARADIS UNOS DE OTROS Y COLOCARLOS SOBRE UNA BANDEJA DE HORNO FORRADA CON PAPEL DE HORNEAR<br>8º:HORNEAR DURANTE 30 MINUTOS HASTA QUE SE QUEDEN CRUJIENTES. SERVIR EN UN PLATO Y ADEREZAR CON LIMÓN Y PEREJIL","45 MINUTOS","FACIL","media/imagenes/filetes_coliflor_empanados.jpg"),


/*RECETA 8*/
("CREPES SALADOS CON HUEVO FRITO","CENA","40G TORTITAS PROTEICAS<br>115ML AGUA<br>5G ACEITE DE COCO<br>1 HUEVO<br>1 LONCHAS PECHUGA DE POLLO O PAVO COCIDO<br>  SAL,PIMIENTA,ENELDO","1º:JUNTA EL PREPARADO PARA TORTITAS PROTEICAS CON EL AGUA EN UN SHAKER O UN RECIPIENTE HONDO.MEZCLAR BIEN HASTA QUE LA MASA QUEDE HOMOGÉNEA<br><br>2º:PONER A CALENTAR LA MITAD DEL ACEITE DE COCO EN UN SARTÉN Y FREÍR DOS CREPES, UNO DETRÁS DE OTRO<br><br>3º: CON LA OTRA MITAD DEL ACEITE DE COCO, FREÍR DOS HUEVOS FRISTOS, A FUEGO MEDIO, HASTA QUE LOS BORDES QUEDEN CRUJIENTES<br><br>4º: EN MEDIO DE CADA CREPE, COLOCAR UNA LONCHA DE PAVO O POLLO Y , SOBRE ELLA, UN HUEVO FRIO. DOBLAR LOS BORDES DEL CREPE COMO SI FUERAN UN SOBRE<br><br>5º: ADEREZAR LOS CREPES SON SAL, PIMIENTA Y ENELDO","20 MINUTOS","FACIL","media/imagenes/crepes_salado.jpg"),

/*RECETA 9*/
("Patatas fritas de calabaza","CENA","1/2 CALABAZA PEQUEÑA<br> 1 CDTA FÉCULA DE MAÍZ<br>1 CDTA ACEITE DE COCO<br>1/2 CDTA AJO EN POLVO <br>1/2 CDTA GUINDILLA EN POLVO<br>1/2 CDTA GUINDILLA EN POLVO <br> 1/2 CDTA SAL MARINA GORDA<br>1 HOJA ROMERO<br>KETCHUP","1º:PRECALIENTE EL HORNO A 200º <br><br> 2º: PELA LA CALABAZA Y CÓRTALA EN FORMA DE PATATAS FRITAS<br><br>3º:VIÉRTELAS EN UN RECIPIENTE GRANDE Y MÉXCLALAS CON LA FÉCULA DE MAÍZ <br><br>4º: AGREGA EL ACEITE DE COCO, EL AJO EN POLVO Y LA GUINDILLA  Y REMUEVE  BIEN<br><br>5º:COLOCA LAS PATATAS DE CALABAZA EN UNA BANDEJA DE HORNO CUBIERTA CON PAPEL DE HORNO SIN QUE SE TOQUEN<br><br>6º: HORNÉALAS 30-35 MINUTOS HASTA QUE QUEDEN CRUJIENTES. DALES LA VUELTA DE VEZ EN CUANDO Y ECHALE SAL AL ACABAR","40 MINUTOS","DIFICIL","media/imagenes/patatas_fritas_calabaza.jpg"),

/*POSTRES*/

/*RECETA 10*/
("BROWNIES PROTEICOS A BASE DE JUDÍAS PINTAS","POSTRE","1 LATA JUDIAS PINTAS'(PESO 256GR)'<br>30G PREOTEÍNA EN POLVO<br>30G CACAO EN POLVO<br>1CDTA PREPARADO PARA HORNEAR<br>70G ESTEVIA<br>40G ACEITE DE COCO<br>1PIZCA SAL<br>50ML AGUA<br>30GR GALLETAS DE CHOCOLATE","1º:PRECALENTAR EL HORNO(ARRIBA Y ABAJO) A180º<br><br>2º:ESCURRIR LAS JUDÍAS CON AYUDA DE UN COLADOR Y LAVAR BIEN CON AGUA<br><br>3º:COLOCAR TODOS LOS INGREDIENTES EN UN ROBOT DE COCINA O BATIDORA HASTA QUE QUEDE UNA MEZCA HOMOGÉNEA.RECOGER LOS BORDER QUE SOBRESALGAN SON AYUDA DE UNA ESPÁTULA Y SEGUIR MEZCLANDO<br><br>4º:FORRAR UNA PEQUEÑA SUPERFICIE'(20X20CM)' CON PAPEL DE HORNEARM O BIEN ENGRASARLA.REPARTIR LA MASA POR ENCIMA Y ESPOLVOREAR CON CHIPS DE CHOCOLATE<br><br>5º:HORNEAR DURANTE 30 MINUTOS. LOS BROWNIES DEBERÍAN ESTAR TIERNOS, AUNQUE CON EL TIEMPO SE VAN ENDURECIENDO UN POCO<br><br>6º: DEJAR ENFRIAR Y CORTAR EN DIFERENTES UNIDADES. RESERVAR EN EL FRIGORÍFICO PARA QUE TENGAN UN MEJOR SABOR","45 MINUTOS","FACIL","media/imagenes/brownies_proteicos.jpg"),

/*RECETA 11*/
("FLAN PROTEICO DE VAINILLA","POSTRE","1 HUEVO<br> 100ML AGUA<br>20G PROTEINA WHEY VAINILLA<br>1CDA FLAVOUR KICK VAINILLA<br>100ML LECHA DESNATADA<br>1RAMITA VAINILLA<br>SIROPE DE CARAMELO SIN AZUCAR","1º:PRECALENTAR EL HORNO '(ARRIBA Y ABAJO)' A 175º<br><br>2º:MEZCLAR EN UN RECIPIENTE EL HUEVO, EL AGUA, LA PROTEÍNA WHEY Y EL FLAVOUR KICK HASTA QUE QUEDE UNA MEZCLA HOMOGÉNEA,APARTAR<br><br>3º:AÑADIR LA LECHE A UNA OLLA. RALLAR VAINILLA DE LA RAMITA Y ECHAR JUNTO CON LA LECHE. COCINAR SUAVEMENTE<br><br>4º: FILTRAR LA LECHE CON AYUDA DE UN COLADOR Y AÑADIR A LA MEZCLA ANTERIOR DE HUEVO. BATIR TODO JUNTO<br>v5º: VERTER LA MASA EN UN MOLDE DE HORNO BIEN PROFUNDO Y CUBRIR CON PAPEL DE ALUMINIO<br><br>6º:COLOCAR EL MOLDE SOBRE UNA BANDEJA DE HORNO. CUBRIR LA BANDEJA DE HORNO CON AGUA PARA QUE LA MITAD DEL CONTENIDO DEL MOLDE SE HAGA AL BAÑO MARIA<br><br> 7º:COLOCAR EL FLAN DURANTE 50 MINUTOS. A CONTINUACIÓN, DEJAR ENFRIAR<br><br>8º: RECORTAR LAS PARTES SOBRESALIENTE DEL MOLDE CON AYUDA DE UN CUCHILLO. ADEREZAR AL GUSTO CON SIROPE DE CARAMELO Y SERVIR","60 MINUTOS","MEDIO","media/imagenes/flan_vainilla.jpg"),

/*RECETA 12*/
("HELADO PROTEICO DE COCO CON ARÁNDANOS","POSTRE"," 30G HELADO PROTEICO SABOR A COCO<br>35ML AGUA<br>25GR ARÁNDANOS<br>12.5ML AGUA<br>1/2 CUCHARADA ALMIDÓN <br>COCO RALLADO","1º:AÑADIR A UN RECIPIENTE EL HELADO PROTEICO EN POLVO JUNTO CON AGUA. MEZCLAR HASTA QUE QUEDE A PUNTO DE NIEVE Y SIN GRUMOS A LA VISTA<br><br>2º:DEJAR 3/4 PARTES DE LA MASA DE HELADO EN UN RECIPIENTE TIPO TUPPER. LA PARTE RESTANTE, RESÉRVALA EN LA NEVERA PARA MAS TARDE<br><br>3º:DEJAR ENFRIAR EL TUPPER DURANTE UN MÍNIMO DE 4 HORAS<br><br>4º:MIENTAS TANTO, AÑADE LOS 150G DE ARÁNDANOS A UNA OLLA CON AGUA Y PONLA A HERVIR DURANTE 5 MINUTOS. MEZCLA EL ALMIDÓN CON DOS CUCHARADAS DE AGUA Y AÑÁDELE LOS ARÁNDANOS HASTA QUE LA SALSA ESPESA. TRITURAR LOS ARÁNDANOS CON LA AYUDA DE UN TENEDOR. RESERVAR<br><br>5º:SACAR EL HELADO. VERTER LA SALSA Y EL RESTO DE 50G DE ARÁNDANOS SOBRE LA SUPERFIFICIE DEL MISMO. CUBRIR EL RESTO CON LA MASA DE HELADO<br><br>6º:PONER A ENFRIAR DE NUEVO DURANTE UN MÍNIMO DE 2 HORAS<br><br>7º:DEJAR DESCONGELAR UN POCO EL HELADO ANTES DE SERVIR. DECORAR CON COCO RALLADO, AL GUSTO","20 MINUTOS","FACIL","media/imagenes/helado_coco.jpg"),

/*ENSALADAS*/

/*RECETA 13*/
("ENSALADA DE CUSCÚS CON ATÚN","ENSALADA","60G CUSCÚS SECO<br>100ML CALDO DE VERDURAS,CALIENTE<br>80G ATÚN EN ACEITE<br>1/2 LIMÓN<br>SAL<br>PIMIENTA<br>6 TOMATES CHERRY <br>1/2 AGUACATE<br>1/2 MANOJO PEREJIL<br>2 PEPERONNI<br>1 HUEVO COCIDO","1º:EN UN GRAN CUENCO, CUBIR EL CUCÚS CON EL CALDO DE VERDURAS CALIENTE Y DEJAR QUE ABSORVA Y SE HINCHE DURANTE 10 MINUTOS<br><br>2º: ESCURRE EL CONTENIDO DE LA LATA DE ATÚN, CONSERVANDO EL ACEITE<br><br>3º:MEZCLAR EL ACEITE DEL ATÚN CON JUGO DE LIMÓN,SAL Y PIMIENTA PARA ELABORAR EL ALIÑO<br><br>4º: CORTAR EL TOMATE Y EL AGUACATE EN TROZOS. PICAR EL PEREJIL<br><br>5º:AÑADIR LAS VERDURAS AL CUSCÚS. VERTER LUEGO EL ALIÑO Y MEZCLAR<br>6º: SAZONAR AL GUSTO. AÑADIR HUEVO Y PEPPERONI A LA ENSALADA","20 MINUTOS","FACIL","media/imagenes/ensalada_cuscus_atun.jpg"),

/*RECETA 14*/
("ENSALADA DE GARBANZOS","ENSALADA","250 G GARBANZOS EN LATA <br>5 TOMATES CHERRY <br> 100G PEPINO<br>20 ACEITUNAS<br>1 CEBOLLA ROJA PEQUEÑA<br>1CDA ACEITE DE OLIVA<br>1CDA VINAGRE DE MANZANA <br>1RAMO PEREJIL FRESCO<br>SAL<br>PIMIENTA<br>OPCIONAL ZUMO DE LIMÓN","1º: CUELA LOS GARBANZOS Y VIÉRTELOS EN UNA ENSALADERA<br><br>2º:CORTA LOS TOMATE EN CUARTOS, LOS PEPINOS EN DADOS, LAS ACEITUNAS POR LA MITAD Y LA CEBOLLA EN FINAS TIRAS. PICA EL PEREJIL<br><br>3º: AGREGA TODAS LAS VERDURAS A LA ENSALADERA.AÑADE ACEITE DE OLVIDA,VINAGRE DE MANZANA, SAL Y PIMIENTA. MÉZCLALO TODO BIEN<br>VIERTE ZUMO DE LIMÓN AL GUSTO","10 MINUTOS","MEDIO","media/imagenes/ensalada_De_garbanzos.jpg");

ALTER IGNORE TABLE  Receta ADD UNIQUE INDEX(Nombre,Tipo,Ingredientes,Pasos,Tiempo_estimado,Nivel_Dificultad,Imagen);











/*INTRODUCIMOS UN USUARIO ADMINISTRADOR*/

INSERT INTO Administrador(Usuario,Contrasenia)
VALUES
("admin","admin1234");



